### ISSUE TITLE
Some snippets do not work

### ISSUE THREAD

**Issue by vitoranguia** [Andr3as/Codiad-CompletePlus#11]
Hello, in a JavaScript (.js) file I can use [javascript.snippets](https://github.com/Andr3as/Codiad-CompletePlus/blob/master/extensions/snippets/javascript.snippets), but I can not use [javascript-jquery.snippets](https://github.com/Andr3as/Codiad-CompletePlus/blob/master/extensions/snippets/javascript-jquery.snippets).

In a C or C++ (.c, .cpp and .h) file I can use [c_cpp.snippets](https://github.com/Andr3as/Codiad-CompletePlus/blob/master/extensions/snippets/c_cpp.snippets), but I can not use [c.snippets](https://github.com/Andr3as/Codiad-CompletePlus/blob/master/extensions/snippets/c.snippets).

System: Debian 9.3, PHP 7.0.27-0, Google Chrome 64.0.3282.186, Mozilla Firefox 52.6.0, Codiad v.2.8.4 and CompletePlus v0.8.5.

Thank you.

**Comment by Andr3as** [comment]
Fixed with b1f0430
Thanks for the bug report.
