### ISSUE TITLE
Autocomplete starter problems

### ISSUE THREAD

**Issue by nickbe** [Andr3as/Codiad-CompletePlus#4]
I installed the autocomplete plugin, but since then I cannot find out how to use it.
From what I saw in the files there should be quite a good PHP support, but codiad
does not seem to recognize or suggest anything at all.

Could you please provide some start how to?

**Comment by Andr3as** [comment]
Open a php file, write your code and if you want to autocomplete a command hit "Ctrl-Space" and you should see something like this: 
![complete_starter](https://cloud.githubusercontent.com/assets/4389878/6199949/cf6f1db2-b460-11e4-8651-ce643d91a5e4.JPG)

Some snippets support tabstops; to jump to the next use "Tab".

Try the latest version, I fixed a bug recently.

**Comment by nickbe** [comment]
I'm working with the latest nightly of codiad.
This morning the complete function worked as expected, but suddenly it won't.
The again at some point it works and only minutes later it won't.
Am Sa., Febr. 14, 2015 15:53 schrieb Andr3as : Open a php file, write your code and if you want to autocomplete a command hit "Ctrl-Space" and you should see something like this: 
 (https://cloud.githubusercontent.com/assets/4389878/6199949/cf6f1db2-b460-11e4-8651-ce643d91a5e4.JPG)
 Some snippets support tabstops; to jump to the next use "Tab".
 Try the latest version, I fixed a bug recently.

**Comment by Andr3as** [comment]
Did you notice some similarities? File modes it doesn't work?

**Comment by Andr3as** [comment]
I noticed a bug too, but I don't find any solution. Best to reload the page (Sry, annoying, I know).

**Comment by avlysenko** [comment]
On a mac, "Ctrl-Space" is Spotlight, don't understand how to activate auto-completion?

**Comment by Andr3as** [comment]
Officially for [Yosemite](https://support.apple.com/kb/PH18799?locale=en_US&viewlocale=en_US) it's "Command-Space" for Spotlight, but there are several ways to solve your problem:
- Hardcode a new keybinding [here](https://github.com/Andr3as/Codiad-CompletePlus/blob/master/init.js#L108)
- Use the [CodeSettings](https://github.com/Andr3as/Codiad-CodeSettings) plugin from me
- Change your Spotlight keybinding on your system

**Comment by avlysenko** [comment]
I live in Russia, so the "cmd+space" works as the switching of keyboard layout (default (and in other countries too)), and the Spotlight is called "ctrl+space". 

CodeSettings — solved my problem. 

Thank you!
