### ISSUE TITLE
random inserting code on keystroke

### ISSUE THREAD

**Issue by TheTesla** [Andr3as/Codiad-CompletePlus#6]
It is constantly crashing: On ctrl+space a proposal is shown, but there is no way to insert it. It is inserting, manipulating and deleting code randomly on every keystroke.

**Comment by Andr3as** [comment]
Which version of codiad and CompletePlus do you use? We fixed a similar bug (Codiad/Codiad#913) in the lastest version. Please select a proper title next time.

**Comment by TheTesla** [comment]
Yes, it was the newest completeplus version, but 2.7.2 of codiad because I had some problems with master. Now I tried master again and it worked, thanks.
