### ISSUE TITLE
Detail features

### ISSUE THREAD

**Issue by wernight** [Andr3as/Codiad-CompletePlus#7]
Could you detail some of the features it has (e.g. does it replace or enhanced existing completion and some examples), and also possibly link to some plugins extending it?

**Comment by Andr3as** [comment]
It actually replaces the existing completion. A basic support for php and other snippets is included. The only plugin I know is [Include](https://github.com/Andr3as/Codiad-Include).

For an example see the following picture:
![complete_starter](https://cloud.githubusercontent.com/assets/4389878/16547303/484a9d88-4169-11e6-866f-29cd608784e7.JPG)

**Comment by wernight** [comment]
That's pretty cool. Just to promote your plugin, I'd put a few side-by-side of Codiad vs CompletePlus for some use cases.

**Comment by Andr3as** [comment]
Done. Thanks for the notice.
