### ISSUE TITLE
Plugin unusable

### ISSUE THREAD

**Issue by fishgrind** [Andr3as/Codiad-CompletePlus#8]
Hey,

I'm having a problem with autocomplete. I have updated everything including Codiad to the latest versions. (codiad version 2.7.4 commit: 58ed33672c4fb5040ab79204b039b31c084a0e19 and CompletePlus v0.8.3)

When using autocomplete it doesn't really suggest an autocomplete it just chooses whatever it thinks is best and so i cant really type anything without it being changed.

It starts by showing a list, which is good, but if it doesn't match anything, instead of just disappearing it changes what i have typed so far and thus there is no way i can type anything else.

for example, when i try to type '**test**',

after typing '**te**' it shows the suggestion list as in my attachment, but as soon as type '**tes**' it just changes it to '**items**'

![image](https://cloud.githubusercontent.com/assets/10580489/17386700/6c25f774-59ed-11e6-9c05-c50c59a3bbb7.png)

I have tested it in a few browsers but it has this problem everywhere, also on different computers. Also after it has auto completed something, ctrl-z doesn't work either, it just keeps auto completing by itself. I have tried removing all other plugins too, that didn't work either.

by the way my console shows this warning:

> 'Automatically scrolling cursor into view after selection change this will be disabled in the next version set editor.$blockScrolling = Infinity to disable this message    ace.js:1'

**Comment by jonmlas** [comment]
I second demotion that! It's pretty useless and makes typing worse. Why can't it behave like Dreamweaver or any other code editors.

**Comment by Andr3as** [comment]
The problem you describe is actually a feature. See issue #1. I understand this might be annoying. I created an option in the settings to disable it.

**Comment by fishgrind** [comment]
@Andr3as thanks!

Just updated the plugin and it works great now! Thanks for the update, appreciated!
