### ISSUE TITLE
Cannot make the plugin work

### ISSUE THREAD

**Issue by nickbe** [Andr3as/Codiad-CompletePlus#9]
After installing the current codiad version and the completeplus plugin there seems no autocomplete function at all.

I tried this with a PHP script. I guess a simple '$ret = explode' and the ctrl-space should open a dropdown with all the parameters but all I see is a simple 'explode'. Trying a '$ret = fil' should list the files functions but there's nothing at all. 

What am i doing wrong here? Does the plugin collide with other plugins?

**Comment by nickbe** [comment]
Ok, so I deinstalled all other plugins and then reinstalled completeplus. After that it seems everything works as expected. So one of the other plugins is blocking CompletePlus :( - but which one.

Have you any idea which one might be the troublemaker here?

**Comment by Andr3as** [comment]
I know currently no incompatibility. Sometimes ComplePlus needs just a reload of Codiad. Do you have a list of the installed plugins?

**Comment by nickbe** [comment]
Just a couple of minutes ago I found out how to solve the problem.
Very strange and simple at the same time.

If I install/reinstall completeplus after I installed other plugins and reload codiad then it works.
if other plugins are installed after completeplus then it refuses to work. Not matter what I do.

So it works and you could maybe write a comment about this effect.
But there has to be a reason for that.

**Comment by Andr3as** [comment]
Great, it works for you.

I can't reproduce your result. I installed CompletePlus on a fresh Codiad installation and several plugins after CompletePlus. I reloaded and everything works.

**Comment by nickbe** [comment]
I only I knew why I had this problems. But I can't tell. I only know that I had to reinstall the plugin and everything worked as expected.
